# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sepcor_rcpp <- function(E, W, n_rows, tol, maxiter, verbose) {
    .Call('_sepcor_sepcor_rcpp', PACKAGE = 'sepcor', E, W, n_rows, tol, maxiter, verbose)
}

sepcov_rcpp <- function(E, n_rows, tol, maxiter, verbose) {
    .Call('_sepcor_sepcov_rcpp', PACKAGE = 'sepcor', E, n_rows, tol, maxiter, verbose)
}

prof_log_lik_rcpp <- function(Sigma_chol, E) {
    .Call('_sepcor_prof_log_lik_rcpp', PACKAGE = 'sepcor', Sigma_chol, E)
}

ll_grad_UV <- function(E, U, V) {
    .Call('_sepcor_ll_grad_UV', PACKAGE = 'sepcor', E, U, V)
}

ll_grad_W_inv <- function(W, E, U, V) {
    .Call('_sepcor_ll_grad_W_inv', PACKAGE = 'sepcor', W, E, U, V)
}

